### ISSUE TITLE
Readme: Finish Setting up Locally: Installation section.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Word-Bank#4]
Please include the steps to install the application locally.

**Comment by agarwal2011** [comment]
i want to take it up!

**Comment by praveenscience** [comment]
@agarwal2011 You can start working! 🔥

**Comment by agarwal2011** [comment]
Installation  should be easy so that more person can access it. We can design it for both mobile and laptop purpose so any person can excess the word if it does not have the device to ...

**Comment by praveenscience** [comment]
Okay... So?

**Comment by praveenscience** [comment]
https://github.com/agarwal2011/Word-Bank-Readme.git
