### ISSUE TITLE
Readme: Finish Contributions section.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Word-Bank#6]
Please add the contribution guidelines for this. A good reference will be: [Rezume/CONTRIBUTING](https://github.com/CatsInTech/Rezume/blob/master/CONTRIBUTING.md).

**Comment by AbhiVikrant** [comment]
I will do this

**Comment by praveenscience** [comment]
@AbhiVikrant You can start working! 🔥

**Comment by praveenscience** [comment]
https://github.com/AbhiVikrant/Word-Bank-Readme/
